[[redirects]]
  from = "/api/*"
  to = "https://nodejs211.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

  [[redirects]]
  from = "/images/*"
  to = "https://nodejs211.dszcbaross.edu.hu/images/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}